-- e-Yantra Supabase Schema
-- Run this in the Supabase SQL Editor

-- 1. Create Themes Table
CREATE TABLE IF NOT EXISTS public.themes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    tagline TEXT,
    summary TEXT,
    accent_color TEXT,
    official_url TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert the 7 official e-Yantra themes
INSERT INTO public.themes (id, slug, name, tagline, accent_color, display_order) OVERRIDING SYSTEM VALUE VALUES 
(1, 'lq', 'Logic Quest', 'Theme 01', '#3B82F6', 1),
(2, 'kd', 'Khoj-o-Drone', 'Theme 02', '#10B981', 2),
(3, 'sc', 'Strata Cobot', 'Theme 03', '#EF4444', 3),
(4, 'he', 'Hola The Explorer', 'Theme 04', '#F59E0B', 4),
(5, 'nv', 'Niti Vahan', 'Theme 05', '#8B5CF6', 5),
(6, 'eb', 'Echo Balancer', 'Theme 06', '#EC4899', 6),
(7, 'pb', 'PacBot', 'Theme 07', '#14B8A6', 7)
ON CONFLICT (slug) DO NOTHING;

-- 2. Create Teams Table
CREATE TABLE IF NOT EXISTS public.teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    theme_id BIGINT REFERENCES public.themes(id) ON DELETE SET NULL,
    official_eyantra_id TEXT,
    description TEXT,
    status TEXT DEFAULT 'forming',
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (Row Level Security) but allow all operations for this demo
ALTER TABLE public.themes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access to themes" ON public.themes;
CREATE POLICY "Allow public read access to themes" ON public.themes FOR SELECT USING (true);

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access to teams" ON public.teams;
CREATE POLICY "Allow public read access to teams" ON public.teams FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated insert to teams" ON public.teams;
CREATE POLICY "Allow authenticated insert to teams" ON public.teams FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Allow authenticated update to teams" ON public.teams;
CREATE POLICY "Allow authenticated update to teams" ON public.teams FOR UPDATE TO authenticated USING (true);
