-- ARC Mission Control Supabase Schema
-- Run this in the Supabase SQL Editor

-- 1. Create Themes Table
CREATE TABLE IF NOT EXISTS public.themes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    tagline TEXT,
    summary TEXT,
    accent_color TEXT,
    official_url TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert some default themes
INSERT INTO public.themes (slug, name, tagline, accent_color) VALUES 
('space', 'Space Robotics', 'Reach for the stars', '#3B82F6'),
('agri', 'AgriBot', 'Farming of the future', '#10B981'),
('healthcare', 'MediBot', 'Saving lives with robotics', '#EF4444')
ON CONFLICT (slug) DO NOTHING;

-- 2. Create Teams Table
CREATE TABLE IF NOT EXISTS public.teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    theme_id BIGINT REFERENCES public.themes(id) ON DELETE SET NULL,
    official_eyantra_id TEXT,
    description TEXT,
    status TEXT DEFAULT 'forming',
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (Row Level Security) but allow all operations for this demo
ALTER TABLE public.themes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to themes" ON public.themes FOR SELECT USING (true);

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to teams" ON public.teams FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert to teams" ON public.teams FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update to teams" ON public.teams FOR UPDATE TO authenticated USING (true);
