-- Run this script in the Supabase SQL Editor

-- 1. Add team_id and is_leader columns to the profiles table
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS team_id BIGINT REFERENCES public.teams(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS is_leader BOOLEAN DEFAULT FALSE;

-- 2. Create tasks table
CREATE TABLE IF NOT EXISTS public.tasks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    assigned_to UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    theme_id BIGINT REFERENCES public.themes(id) ON DELETE CASCADE,
    priority TEXT DEFAULT 'medium',
    status TEXT DEFAULT 'pending',
    due_date DATE,
    due_time TIME,
    marks INTEGER DEFAULT 0 NOT NULL CHECK (marks >= 0),
    obtained_marks INTEGER DEFAULT NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create announcements table
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    theme_id BIGINT REFERENCES public.themes(id) ON DELETE SET NULL,
    target_role TEXT,
    is_pinned BOOLEAN DEFAULT FALSE,
    requires_acknowledgement BOOLEAN DEFAULT FALSE,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3.5 Create announcement_acknowledgements table
CREATE TABLE IF NOT EXISTS public.announcement_acknowledgements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id BIGINT REFERENCES public.announcements(id) ON DELETE CASCADE,
    profile_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    acknowledged_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure theme_id exists if the tables were already created previously
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS theme_id BIGINT REFERENCES public.themes(id) ON DELETE CASCADE;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS theme_id BIGINT REFERENCES public.themes(id) ON DELETE SET NULL;

-- Enable RLS but allow all operations for this demo
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on tasks" ON public.tasks;
CREATE POLICY "Allow public all on tasks" ON public.tasks FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on announcements" ON public.announcements;
CREATE POLICY "Allow public all on announcements" ON public.announcements FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.announcement_acknowledgements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on acks" ON public.announcement_acknowledgements;
CREATE POLICY "Allow public all on acks" ON public.announcement_acknowledgements FOR ALL USING (true) WITH CHECK (true);

-- Allow updating profiles so Team Leaders can add members
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public update to profiles" ON public.profiles;
CREATE POLICY "Allow public update to profiles" ON public.profiles FOR UPDATE USING (true) WITH CHECK (true);

-- 4. Insert the 7 custom themes from the Leaderboard
-- We use ON CONFLICT to avoid deleting themes that teams are already assigned to!
INSERT INTO public.themes (id, slug, name, tagline, accent_color, display_order) OVERRIDING SYSTEM VALUE VALUES 
(1, 'lq', 'LQ Theme', 'Theme 01', '#3B82F6', 1),
(2, 'kd', 'KD Theme', 'Theme 02', '#10B981', 2),
(3, 'sc', 'SC Theme', 'Theme 03', '#EF4444', 3),
(4, 'he', 'HE Theme', 'Theme 04', '#F59E0B', 4),
(5, 'nv', 'NV Theme', 'Theme 05', '#8B5CF6', 5),
(6, 'eb', 'EB Theme', 'Theme 06', '#EC4899', 6),
(7, 'pb', 'PB Theme', 'Theme 07', '#14B8A6', 7)
ON CONFLICT (id) DO UPDATE SET 
    slug = EXCLUDED.slug, 
    name = EXCLUDED.name,
    tagline = EXCLUDED.tagline,
    accent_color = EXCLUDED.accent_color,
    display_order = EXCLUDED.display_order;

-- Quick fix to reassign any unassigned teams back to HE Theme just in case they were lost
UPDATE public.teams SET theme_id = 4 WHERE theme_id IS NULL;
